### ISSUE TITLE
cannot run command: MongoRunner Editor

### ISSUE THREAD

**Issue by dong2590** [zhaoyi0113/mongodb-runner#31]
>  System: MacOS 10.14.3
>  VSCode: 1.31.0

### Steps to Reproduce
1. install mongoRunner from extension market
2. run `MongoRunner Editor`

Error tips: 
![image](https://user-images.githubusercontent.com/1455816/52694593-32ce4900-2fa5-11e9-8d99-e70fd757bfe5.png)

### Output logs
```javascript
[2019-02-13 15:34:49.108] [exthost] [error] TypeError: Cannot read property 'colName' of undefined
	at launchMREditor (/Users/dong2590/.vscode/extensions/joeyyizhao.mongo-runner-0.5.5/client/src/commands.js:183:25)
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:485:959)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486:443)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644:118)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:744)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:322)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:155)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638:960
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38:994
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:113)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:213)
	at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170:434)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) mongoRunner.launchEditor
```

**Comment by zhaoyi0113** [comment]
Could you let me know from where you open mongo runner editor? Like from `database`, `collection` or `index`? It would be good if you can send a screenshot on this.

**Comment by zhaoyi0113** [comment]
I see what you issue. Could you try to launch mongodbrunner editor from the context menu on the left panel? 

![image](https://user-images.githubusercontent.com/3355579/52748368-77f08a80-303a-11e9-8ee9-3693fb0c78d6.png)

**Comment by dong2590** [comment]
> Could you let me know from where you open mongo runner editor? Like from `database`, `collection` or `index`? It would be good if you can send a screenshot on this.

![image](https://user-images.githubusercontent.com/1455816/52767322-1d205880-3065-11e9-9a78-785a62afa09b.png)

**Comment by zhaoyi0113** [comment]
fixed in the latest version.
