### ISSUE TITLE
I can't connect to mongodb.

### ISSUE THREAD

**Issue by linuxoid69** [zhaoyi0113/mongodb-runner#46]
vs code 1.38.1

```
[2019-10-03 16:36:09.374] [exthost] [error] TypeError: Cannot read property 'provider' of undefined
	at refreshAllConnections (/home/rmt/.vscode/extensions/joeyyizhao.mongo-runner-0.5.8/client/src/commands.js:269:40)
	at _executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:518:163)
	at _.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:518:538)
	at d._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623:396)
	at d._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:623:88)
	at d._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:783)
	at d._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:605)
	at define.constructor._protocol.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:618:791)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:579)
	at i.constructor.e.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:484)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:579)
	at x._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:191:17)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:188:116)
	at u.fire 

(/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at f.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:184:17)
	at define.constructor._register._socket.onData.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:183:372)
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:192:491)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) mongoRunner.refresh
```

**Comment by zhaoyi0113** [comment]
Looks like your `Mongodb Runner` extension is not activated. Could you try to restart vscode? If it doesn't help. could you share your vscode configuration for `Mongodb Runner`?

**Comment by linuxoid69** [comment]
> Looks like your `Mongodb Runner` extension is not activated. Could you try to restart vscode? If it doesn't help. could you share your vscode configuration for `Mongodb Runner`?

Mongodb Runner extension is activated.
I tried to restart vscode.

```
    "mongoRunner": {
        "connections": [
            {
                "name": "connection2",
                "url": "mongodb://localhost:27017"
            }
        ]
    }
```

**Comment by zhaoyi0113** [comment]
Your configuration looks right. Could you let me know your mongodb server version? And do you get the error when you right click the `connection2` under MONGO RUNNER panel then click `Connect`?

**Comment by linuxoid69** [comment]
MongoDB v4.2.0. I have the error still exists

**Comment by linuxoid69** [comment]
> Your configuration looks right. Could you let me know your mongodb server version? And do you get the error when you right click the `connection2` under MONGO RUNNER panel then click `Connect`?

Hm, on my home laptop the extension works О_о

**Comment by zhaoyi0113** [comment]
Is there any network issue causing this?

**Comment by linuxoid69** [comment]
> > Your configuration looks right. Could you let me know your mongodb server version? And do you get the error when you right click the `connection2` under MONGO RUNNER panel then click `Connect`?
> 
> Hm, on my home laptop the extension works О_о

In-home I have vs code 1.39.1
At work, I updated vs code to version 1.39.1 and the error disappears.

**Comment by zhaoyi0113** [comment]
oh, good to know that your issues disappears. Feel free to contact me if you are running into any issues.
